# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f14c7ca1e89043d51b3f5a9546d41f4a"
name = "final-product-reservation"
handle = "final-product-reservation"
application_url = "https://final-product-reservation.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,read_customers"

[auth]
redirect_urls = [ "https://final-product-reservation.onrender.com/api/auth" ]

[pos]
embedded = false
